spring.application.name=backend


spring.datasource.url=jdbc:mysql://localhost:3306/backforge?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

# Razorpay Configuration
razorpay.key.id=rzp_test_51P7kO9H3JkL0M
razorpay.key.secret=ndbnckjfbkjbfjbnamchcbdlfnsncmxmnvcnsvc123456
